<?php echo $this->getContent() ?>

<div align="center" class="welcome">

	<h1>KIRIM.EMAIL</h1>

	<p>Cara TERMUDAH Meningkatkan Penjualan Dengan Mengumpulkan Pelanggan Tetap Anda Di Satu Tempat, Sehingga Bisa Anda Hubungi Dimanapun & Kapanpun Anda Ingin Menjual Sesuatu...</p>

	<?php echo \Phalcon\Tag::linkTo(array("subscribes/new", "Create a Subscriber!", "class" => "btn btn-lg btn-primary")); ?>
</div>